# This is a basic workflow to help you get started with Actions

name: QEMU for W32

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: mingw32
          install: >-
            git
            wget
            base-devel 
            mingw-w64-i686-toolchain 
            python 
            ninja
            mingw-w64-i686-gtk3
            mingw-w64-i686-SDL2 
            mingw-w64-i686-libslirp

      - shell: msys2 {0}
        name: build qemu
        run: |
          git clone https://gitlab.com/qemu-project/qemu.git
          cd qemu
          git submodule init
          git submodule update --recursive
          ./configure --prefix=/d/123/qemu-w32 --enable-sdl --enable-gtk
          make install

      - uses: actions/upload-artifact@v4
        with:
          name: QEMU
          path: /d/123/qemu-w32
           
          
    
